### ISSUE TITLE
Find a new base image

### ISSUE THREAD

**Issue by ubyndr** [OBASKTools/pipeline-updatetriplestore#2]
`FROM yyz1989/rdf4j` hasn't been updated for 4 years, and now we, at least I, cannot re-build the image from that base image. @hkir-dev @dosumis fyi

**Comment by hkir-dev** [comment]
In the compose we are using `eclipse/rdf4j-workbench:3.7.7` instead of `yyz1989/rdf4j`. Can we use it in here as well?
